# -*- coding: utf-8 -*-
"""DUSt3R_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1H0rYHcL7Jz-T-vj4Z-Gld415f-xU7h
"""

import torch
print("✅ CUDA 사용 가능 여부:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("✅ GPU 모델:", torch.cuda.get_device_name(0))
else:
    print("🚨 GPU가 감지되지 않음! Colab '런타임 유형 변경'에서 GPU 설정 확인 필요")

!git clone https://github.com/naver/dust3r.git /content/dust3r

!ls /content/dust3r/

!pip install -r /content/dust3r/requirements.txt
!pip install gradio trimesh scipy torch torchvision numpy

!cd /content/dust3r && git submodule update --init --recursive

!python /content/dust3r/demo.py --model_name DUSt3R_ViTLarge_BaseDecoder_512_dpt --device cuda --server_port 7860

